import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const manRopeSans = Manrope({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "HireLoop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${manRopeSans.variable} h-full antialiased`}>
      <body className="h-full">
        <div className="flex flex-col min-h-screen">
          <Navbar></Navbar>
          <main className="flex-1">{children}</main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
